---
sidebar: sidebar 
permalink: task-gcp-enable-data-services.html 
keywords: google buckets, google storage, google cloud storage working environment, google cloud storage buckets 
summary: Dopo aver scoperto i bucket di storage cloud Google in BlueXP, puoi utilizzare i servizi dati NetApp per backup, tiering e sincronizzazione dei dati. 
---
= Utilizza i servizi dati NetApp con i bucket di storage cloud di Google
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver scoperto i bucket di storage cloud Google in BlueXP, puoi utilizzare i servizi dati NetApp per backup, tiering e sincronizzazione dei dati.

* Utilizza *backup e ripristino BlueXP* per eseguire il backup dei dati dai sistemi ONTAP e Cloud Volumes ONTAP on-premise allo storage a oggetti Google Cloud.
+
Per iniziare, vai su Canvas e trascina un ambiente di lavoro on-premise ONTAP o Cloud Volumes ONTAP sul tuo ambiente di lavoro.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Scopri di più sul backup dei dati ONTAP su Google Cloud Storage"^].

* Utilizza il tiering * BlueXP per tiering dei dati inattivi dai cluster ONTAP on-premise allo storage a oggetti Google Cloud.
+
Per iniziare, accedi a Canvas e trascina un ambiente di lavoro ONTAP on-premise sul tuo ambiente di lavoro.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-gcp.html["Scopri di più sul tiering dei dati ONTAP su Google Cloud Storage"^].

* Utilizzare *BlueXP copy and Sync* per sincronizzare i dati da o verso i bucket di storage Google Cloud.
+
Per iniziare, accedi a Canvas e trascina l'ambiente di lavoro di origine nell'ambiente di lavoro di destinazione. L'ambiente di lavoro di Google Cloud Storage può essere l'origine o la destinazione.

+
È inoltre possibile selezionare l'ambiente di lavoro di Google Cloud Storage e fare clic su *Copy & Sync* (Copia e sincronizza) dal pannello Services (servizi) per sincronizzare i dati da o verso i bucket di Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Scopri di più sul servizio di copia e sincronizzazione BlueXP"^].


